# Generated by Django 4.2.8 on 2023-12-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('processed', models.BooleanField(default=False)),
                ('processed_video_file', models.FileField(null=True, upload_to='processed_videos/')),
                ('alarm_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
