# Generated by Django 4.2.8 on 2023-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='alarm_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='processed_video_file',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
    ]
