# -*- coding: utf-8 -*-
"""데이터 전처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ADfvKFPLvDlXXdBfZKNbusYr-6kLsTei
"""

from google.colab import drive
drive.mount('/content/drive')

from moviepy.editor import VideoFileClip, concatenate_videoclips
import os

def make_clip_video(path, save_path, start_t, end_t):
    save_dir = os.path.dirname(save_path)
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    clip_video = VideoFileClip(path).subclip(start_t, end_t)
    clip_video.write_videofile(save_path)

#파일 이름 변경 코드
import os
folder_path = '/content/drive/MyDrive/CCTV/Abnormal/Abnormal'
mp4_files = [f for f in os.listdir(folder_path) if f.endswith('.mp4')]
mp4_files.sort()  # 파일을 정렬하여 이름을 순차적으로 변경합니다.
for i, file in enumerate(mp4_files, start=1):
    # 새 파일명 설정 (1.png, 2.png, ...)
    new_file_name = f"Abnormal_{i}.mp4"
#     # 파일 이름 변경
    os.rename(os.path.join(folder_path, file), os.path.join(folder_path, new_file_name))
print("파일 이름 변경 완료!")

import os
from moviepy.editor import VideoFileClip, concatenate_videoclips

# 비디오 클립 생성 및 저장 함수
def make_clip_video(source_path, save_path, start_t, end_t):
    if not os.path.exists(os.path.dirname(save_path)):
        os.makedirs(os.path.dirname(save_path))
    clip_video = VideoFileClip(source_path).subclip(start_t, end_t)
    clip_video.write_videofile(save_path)

# 클립 결합 및 저장 함수
def combine_and_save_clips(source_path, save_path, clip_names):
    if not os.path.exists(os.path.dirname(save_path)):
        os.makedirs(os.path.dirname(save_path))
    clips = [VideoFileClip(os.path.join(source_path, name)) for name in clip_names]
    combined_clip = concatenate_videoclips(clips)
    combined_clip.write_videofile(save_path)

# 비디오 파일이 있는 폴더 경로
video_folder_path = '/content/drive/MyDrive/CCTV/Abnormal/Abnormal'

# 저장 경로 정의
clips_save_path = "/content/drive/MyDrive/CCTV/Data/clips"
abnormal_save_path = "/content/drive/MyDrive/CCTV/Data/abnormal"
normal_save_path = "/content/drive/MyDrive/CCTV/Data/normal"

# 각 비디오에 대한 클립 생성 및 결합
for idx, video_name in enumerate(os.listdir(video_folder_path)):
    if video_name.endswith('.mp4'):
        video_path = os.path.join(video_folder_path, video_name)
        base_name = os.path.splitext(video_name)[0]

        # 이상행동(abnormal) 및 정상(normal) 클립 생성 및 저장
        abnormal_clip_name = f'{base_name}_abnormal.mp4'
        normal_clip_name = f'{base_name}_normal.mp4'
        make_clip_video(video_path, os.path.join(clips_save_path, abnormal_clip_name), 22, 34)
        make_clip_video(video_path, os.path.join(clips_save_path, normal_clip_name), 4, 16)

        # 생성된 클립 결합 및 저장
        combined_abnormal_path = os.path.join(abnormal_save_path, f'combined_{idx}_abnormal.mp4')
        combined_normal_path = os.path.join(normal_save_path, f'combined_{idx}_normal.mp4')
        combine_and_save_clips(clips_save_path, combined_abnormal_path, [abnormal_clip_name])
        combine_and_save_clips(clips_save_path, combined_normal_path, [normal_clip_name])

from moviepy.editor import VideoFileClip, concatenate_videoclips
import os

def make_clip_video(path, save_path, start_t, end_t):
    clip_video = VideoFileClip(path).subclip(start_t, end_t)
    clip_video.write_videofile(save_path)

base_save_path = '/content/drive/MyDrive/CCTV/clips'
save_path = "/content/drive/MyDrive/CCTV/DATA"
source_path = '/content/drive/MyDrive/CCTV/clips'

# 4 각도
path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_25_BU_SYB_10-04_14-51-46_CA_RGB_DF2_F3.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_25_BU_SYB_10-04_14-51-46_CB_RGB_DF2_F3.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_25_BU_SYB_10-04_14-51-46_CC_RGB_DF2_F3.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_25_BU_SYB_10-04_14-51-46_CD_RGB_DF2_F3.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_081_abnormal_36.mp4'), 22, 34)
make_clip_video(path1, os.path.join(base_save_path, 'b_082_abnormal_30.mp4'), 41, 51)

make_clip_video(path1, os.path.join(base_save_path, 'b_081_normal_36.mp4'), 4, 16)
make_clip_video(path1, os.path.join(base_save_path, 'b_082_normal_30.mp4'), 11, 21)


#2
make_clip_video(path2, os.path.join(base_save_path, 'b_083_abnormal_36.mp4'), 22, 34)
make_clip_video(path2, os.path.join(base_save_path, 'b_084_abnormal_30.mp4'), 41, 51)

make_clip_video(path2, os.path.join(base_save_path, 'b_083_normal_36.mp4'), 4, 16)
make_clip_video(path2, os.path.join(base_save_path, 'b_084_normal_30.mp4'), 11, 21)


#3
make_clip_video(path3, os.path.join(base_save_path, 'b_085_abnormal_36.mp4'), 22, 34)
make_clip_video(path3, os.path.join(base_save_path, 'b_086_abnormal_30.mp4'), 41, 51)

make_clip_video(path3, os.path.join(base_save_path, 'b_085_normal_36.mp4'), 4, 16)
make_clip_video(path3, os.path.join(base_save_path, 'b_086_normal_30.mp4'), 11, 21)


#4
make_clip_video(path4, os.path.join(base_save_path, 'b_087_abnormal_36.mp4'), 22, 34)
make_clip_video(path4, os.path.join(base_save_path, 'b_088_abnormal_30.mp4'), 41, 51)

make_clip_video(path4, os.path.join(base_save_path, 'b_087_normal_36.mp4'), 4, 16)
make_clip_video(path4, os.path.join(base_save_path, 'b_088_normal_30.mp4'), 11, 21)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_081_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_082_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_081_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_082_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_019_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_019_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_083_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_084_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_083_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_084_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_020_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_020_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_085_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_086_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_085_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_086_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_021_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_021_normal_66.mp4"))

#4
abnormal1 = VideoFileClip(os.path.join(source_path, "b_087_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_088_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_087_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_088_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_022_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_022_normal_66.mp4"))

# 3 각도
path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_1_BU_DYA_07-31_16-15-01_CA_RGB_DF2_M1.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_1_BU_DYA_07-31_16-15-04_CB_RGB_DF2_M1.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_1_BU_DYA_07-31_16-15-04_CC_RGB_DF2_M1.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_089_abnormal_36.mp4'), 24, 33)
make_clip_video(path1, os.path.join(base_save_path, 'b_090_abnormal_30.mp4'), 43, 53)

make_clip_video(path1, os.path.join(base_save_path, 'b_089_normal_36.mp4'), 8, 22)
make_clip_video(path1, os.path.join(base_save_path, 'b_090_normal_30.mp4'), 35, 45)


#2
make_clip_video(path2, os.path.join(base_save_path, 'b_091_abnormal_36.mp4'), 24, 33)
make_clip_video(path2, os.path.join(base_save_path, 'b_092_abnormal_30.mp4'), 43, 53)

make_clip_video(path2, os.path.join(base_save_path, 'b_091_normal_36.mp4'), 8, 22)
make_clip_video(path2, os.path.join(base_save_path, 'b_092_normal_30.mp4'), 35, 45)


#3
make_clip_video(path3, os.path.join(base_save_path, 'b_093_abnormal_36.mp4'), 24, 33)
make_clip_video(path3, os.path.join(base_save_path, 'b_094_abnormal_30.mp4'), 43, 53)

make_clip_video(path3, os.path.join(base_save_path, 'b_093_normal_36.mp4'), 8, 22)
make_clip_video(path3, os.path.join(base_save_path, 'b_094_normal_30.mp4'), 35, 45)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_089_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_090_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_089_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_090_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_023_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_023_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_091_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_092_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_091_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_092_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_024_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_024_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_093_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_094_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_093_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_094_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_025_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_025_normal_66.mp4"))

# 3 각도
path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_1_BU_DYB_08-06_14-31-39_CC_RGB_DF2_M1.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_1_BU_DYB_08-06_14-31-40_CA_RGB_DF2_M1.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_1_BU_DYB_08-06_14-31-40_CB_RGB_DF2_M1.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_001_abnormal_36.mp4'), 25, 32)
make_clip_video(path1, os.path.join(base_save_path, 'b_002_abnormal_30.mp4'), 47, 55)

make_clip_video(path1, os.path.join(base_save_path, 'b_001_normal_36.mp4'), 6, 23)
make_clip_video(path1, os.path.join(base_save_path, 'b_002_normal_30.mp4'), 33, 45)


#2
make_clip_video(path2, os.path.join(base_save_path, 'b_003_abnormal_36.mp4'), 25, 32)
make_clip_video(path2, os.path.join(base_save_path, 'b_004_abnormal_30.mp4'), 47, 55)

make_clip_video(path2, os.path.join(base_save_path, 'b_003_normal_36.mp4'), 6, 23)
make_clip_video(path2, os.path.join(base_save_path, 'b_004_normal_30.mp4'), 33, 45)


#3
make_clip_video(path3, os.path.join(base_save_path, 'b_005_abnormal_36.mp4'), 25, 32)
make_clip_video(path3, os.path.join(base_save_path, 'b_006_abnormal_30.mp4'), 47, 55)

make_clip_video(path3, os.path.join(base_save_path, 'b_005_normal_36.mp4'), 6, 23)
make_clip_video(path3, os.path.join(base_save_path, 'b_006_normal_30.mp4'), 33, 45)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_001_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_002_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_001_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_002_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_001_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_001_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_003_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_004_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_003_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_004_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_002_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_002_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_005_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_006_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_005_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_006_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_003_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_003_normal_66.mp4"))

# 3 각도
path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_28_BU_SYB_10-04_14-40-51_CD_RGB_DF2_F3.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_28_BU_SYB_10-04_14-40-51_CC_RGB_DF2_F3.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_28_BU_SYB_10-04_14-40-51_CB_RGB_DF2_F3.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_28_BU_SYB_10-04_14-40-51_CA_RGB_DF2_F3.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_007_abnormal_36.mp4'), 22, 36)
make_clip_video(path1, os.path.join(base_save_path, 'b_008_abnormal_30.mp4'), 41, 49)

make_clip_video(path1, os.path.join(base_save_path, 'b_007_normal_36.mp4'), 2, 21)


#2
make_clip_video(path2, os.path.join(base_save_path, 'b_009_abnormal_36.mp4'), 22, 36)
make_clip_video(path2, os.path.join(base_save_path, 'b_010_abnormal_30.mp4'), 41, 49)

make_clip_video(path2, os.path.join(base_save_path, 'b_009_normal_36.mp4'), 2, 21)


#3
make_clip_video(path3, os.path.join(base_save_path, 'b_011_abnormal_36.mp4'), 22, 36)
make_clip_video(path3, os.path.join(base_save_path, 'b_012_abnormal_30.mp4'), 41, 49)

make_clip_video(path3, os.path.join(base_save_path, 'b_011_normal_36.mp4'), 2, 21)

#4

make_clip_video(path4, os.path.join(base_save_path, 'b_013_abnormal_36.mp4'), 22, 36)
make_clip_video(path4, os.path.join(base_save_path, 'b_014_abnormal_30.mp4'), 41, 49)

make_clip_video(path4, os.path.join(base_save_path, 'b_013_normal_36.mp4'), 2, 21)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_007_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_008_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_007_normal_36.mp4"))
combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_004_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_004_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_009_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_010_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_009_normal_36.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_005_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_005_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_011_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_012_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_011_normal_36.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_006_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_006_normal_66.mp4"))

#4
abnormal1 = VideoFileClip(os.path.join(source_path, "b_013_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_014_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_013_normal_36.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_007_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_007_normal_66.mp4"))

# 3 각도
path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_28_BU_SMC_08-07_13-31-55_CF_RGB_DF2_F1.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_28_BU_SMC_08-07_13-31-55_CE_RGB_DF2_F1.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_28_BU_SMC_08-07_13-31-55_CD_RGB_DF2_F1.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_015_abnormal_36.mp4'), 34, 54)

make_clip_video(path1, os.path.join(base_save_path, 'b_015_normal_36.mp4'), 2, 30)


#2
make_clip_video(path2, os.path.join(base_save_path, 'b_016_abnormal_36.mp4'), 34, 54)

make_clip_video(path2, os.path.join(base_save_path, 'b_016_normal_36.mp4'), 2, 30)


#3
make_clip_video(path3, os.path.join(base_save_path, 'b_017_abnormal_36.mp4'), 34, 54)

make_clip_video(path3, os.path.join(base_save_path, 'b_017_normal_36.mp4'), 2, 30)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_015_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_015_normal_36.mp4"))


combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_008_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_008_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_016_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_016_normal_36.mp4"))


combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_009_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_009_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_017_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_017_normal_36.mp4"))


combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_010_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_010_normal_66.mp4"))

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_26_BU_SMC_08-07_13-27-34_CF_RGB_DF2_M1.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_26_BU_SMC_08-07_13-27-34_CE_RGB_DF2_M1.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_26_BU_SMC_08-07_13-27-34_CD_RGB_DF2_M1.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_100_abnormal_36.mp4'), 34, 47)

make_clip_video(path1, os.path.join(base_save_path, 'b_100_normal_36.mp4'), 2, 30)
make_clip_video(path1, os.path.join(base_save_path, 'b_101_normal_30.mp4'), 50, 57)

#2
make_clip_video(path2, os.path.join(base_save_path, 'b_102_abnormal_36.mp4'), 34, 47)

make_clip_video(path2, os.path.join(base_save_path, 'b_102_normal_36.mp4'), 2, 30)
make_clip_video(path2, os.path.join(base_save_path, 'b_103_normal_30.mp4'), 50, 57)

#3
make_clip_video(path3, os.path.join(base_save_path, 'b_104_abnormal_36.mp4'), 34, 47)

make_clip_video(path3, os.path.join(base_save_path, 'b_104_normal_36.mp4'), 2, 30)
make_clip_video(path3, os.path.join(base_save_path, 'b_105_normal_30.mp4'), 50, 57)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_100_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_100_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_101_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1,normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_100_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_100_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_102_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_102_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_103_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_101_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_101_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_104_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_104_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_105_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_102_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_102_normal_66.mp4"))

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_23_BU_SMB_09-02_15-50-56_CD_RGB_DF2_M3.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_23_BU_SMB_09-02_15-50-56_CC_RGB_DF2_M3.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_23_BU_SMB_09-02_15-50-56_CB_RGB_DF2_M3.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_23_BU_SMB_09-02_15-50-56_CA_RGB_DF2_M3.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_106_abnormal_36.mp4'), 20, 47)

make_clip_video(path1, os.path.join(base_save_path, 'b_106_normal_36.mp4'), 5, 16)

#2
make_clip_video(path2, os.path.join(base_save_path, 'b_107_abnormal_36.mp4'), 20, 47)

make_clip_video(path2, os.path.join(base_save_path, 'b_107_normal_36.mp4'), 5, 16)

#3
make_clip_video(path3, os.path.join(base_save_path, 'b_108_abnormal_36.mp4'), 20, 47)

make_clip_video(path3, os.path.join(base_save_path, 'b_108_normal_36.mp4'), 5, 16)

# 4
make_clip_video(path3, os.path.join(base_save_path, 'b_109_abnormal_36.mp4'), 20, 47)

make_clip_video(path3, os.path.join(base_save_path, 'b_109_normal_36.mp4'), 5, 16)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_106_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_106_normal_36.mp4"))

combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_103_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_103_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_107_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_107_normal_36.mp4"))


combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_104_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_104_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_108_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_108_normal_36.mp4"))


combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_105_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_105_normal_66.mp4"))

#4
abnormal1 = VideoFileClip(os.path.join(source_path, "b_109_abnormal_36.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_109_normal_36.mp4"))


combined_a = concatenate_videoclips([abnormal1])
combined_n = concatenate_videoclips([normal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_106_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_106_normal_66.mp4"))

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_22_BU_SYB_10-04_14-45-43_CD_RGB_DF2_M3.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_22_BU_SYB_10-04_14-45-43_CC_RGB_DF2_M3.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_22_BU_SYB_10-04_14-45-43_CB_RGB_DF2_M3.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_22_BU_SYB_10-04_14-45-43_CA_RGB_DF2_M3.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_110_abnormal_36.mp4'), 16, 31)
make_clip_video(path1, os.path.join(base_save_path, 'b_111_abnormal_30.mp4'), 37, 50)

make_clip_video(path1, os.path.join(base_save_path, 'b_110_normal_36.mp4'), 4, 14)
make_clip_video(path1, os.path.join(base_save_path, 'b_111_normal_30.mp4'), 32, 36)

#2
make_clip_video(path2, os.path.join(base_save_path, 'b_112_abnormal_36.mp4'), 16, 31)
make_clip_video(path2, os.path.join(base_save_path, 'b_113_abnormal_30.mp4'), 37, 50)

make_clip_video(path2, os.path.join(base_save_path, 'b_112_normal_36.mp4'), 4, 14)
make_clip_video(path2, os.path.join(base_save_path, 'b_113_normal_30.mp4'), 32, 36)
#3
make_clip_video(path3, os.path.join(base_save_path, 'b_114_abnormal_36.mp4'), 16, 31)
make_clip_video(path3, os.path.join(base_save_path, 'b_115_abnormal_30.mp4'), 37, 50)

make_clip_video(path3, os.path.join(base_save_path, 'b_114_normal_36.mp4'), 4, 14)
make_clip_video(path3, os.path.join(base_save_path, 'b_115_normal_30.mp4'), 32, 36)

# 4
make_clip_video(path3, os.path.join(base_save_path, 'b_116_abnormal_36.mp4'), 16, 31)
make_clip_video(path3, os.path.join(base_save_path, 'b_117_abnormal_30.mp4'), 37, 50)

make_clip_video(path3, os.path.join(base_save_path, 'b_116_normal_36.mp4'), 4, 14)
make_clip_video(path3, os.path.join(base_save_path, 'b_117_normal_30.mp4'), 32, 36)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_110_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_111_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_110_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_111_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_107_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_107_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_112_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_113_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_112_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_113_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, abnormal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_108_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_108_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_114_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_115_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_114_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_115_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_109_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_109_normal_66.mp4"))

#4
abnormal1 = VideoFileClip(os.path.join(source_path, "b_116_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_117_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_116_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_117_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_109_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_109_normal_66.mp4"))

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_21_BU_SYB_10-04_14-59-45_CD_RGB_DF2_M3.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_21_BU_SYB_10-04_14-59-45_CC_RGB_DF2_M3.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_21_BU_SYB_10-04_14-59-45_CB_RGB_DF2_M3.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_12.절도/C_3_12_21_BU_SYB_10-04_14-59-45_CA_RGB_DF2_M3.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_118_abnormal_36.mp4'), 17, 25)
make_clip_video(path1, os.path.join(base_save_path, 'b_119_abnormal_30.mp4'), 32, 45)

make_clip_video(path1, os.path.join(base_save_path, 'b_118_normal_36.mp4'), 5, 16)
make_clip_video(path1, os.path.join(base_save_path, 'b_119_normal_30.mp4'), 26, 31)

#2
make_clip_video(path2, os.path.join(base_save_path, 'b_120_abnormal_36.mp4'), 17, 25)
make_clip_video(path2, os.path.join(base_save_path, 'b_121_abnormal_30.mp4'), 32, 45)

make_clip_video(path2, os.path.join(base_save_path, 'b_120_normal_36.mp4'), 5, 16)
make_clip_video(path2, os.path.join(base_save_path, 'b_121_normal_30.mp4'), 28, 31)
#3
make_clip_video(path3, os.path.join(base_save_path, 'b_122_abnormal_36.mp4'), 17, 25)
make_clip_video(path3, os.path.join(base_save_path, 'b_123_abnormal_30.mp4'), 32, 45)

make_clip_video(path3, os.path.join(base_save_path, 'b_122_normal_36.mp4'), 5, 16)
make_clip_video(path3, os.path.join(base_save_path, 'b_123_normal_30.mp4'), 28, 31)

# 4
make_clip_video(path3, os.path.join(base_save_path, 'b_124_abnormal_36.mp4'), 17, 25)
make_clip_video(path3, os.path.join(base_save_path, 'b_125_abnormal_30.mp4'), 32, 45)

make_clip_video(path3, os.path.join(base_save_path, 'b_124_normal_36.mp4'), 5, 16)
make_clip_video(path3, os.path.join(base_save_path, 'b_125_normal_30.mp4'), 28, 31)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_118_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_119_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_118_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_119_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_110_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_110_normal_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_120_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_121_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_120_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_121_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, abnormal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_111_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_111_normal_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_122_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_123_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_122_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_123_normal_30.mp4"))


combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_112_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_112_normal_66.mp4"))

#4
abnormal1 = VideoFileClip(os.path.join(source_path, "b_124_abnormal_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_125_abnormal_30.mp4"))

normal1 = VideoFileClip(os.path.join(source_path, "b_124_normal_36.mp4"))
normal2 = VideoFileClip(os.path.join(source_path, "b_125_normal_30.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2])
combined_n = concatenate_videoclips([normal1, normal2])

combined_a.write_videofile(os.path.join(save_path, "bcom_113_abnormal_66.mp4"))
combined_n.write_videofile(os.path.join(save_path, "bcom_113_normal_66.mp4"))

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_53_BU_DYB_10-17_11-14-01_CE_RGB_DF2_F2.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_53_BU_DYB_10-17_11-14-01_CD_RGB_DF2_F2.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_53_BU_DYB_10-17_11-14-01_CC_RGB_DF2_F2.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_53_BU_DYB_10-17_11-14-01_CB_RGB_DF2_F2.mp4'

base_save_path = '/content/drive/MyDrive/CCTV/clips'
save_path = "/content/drive/MyDrive/CCTV/DATA"
source_path = '/content/drive/MyDrive/CCTV/clips'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_118_broken_36.mp4'), 26, 27)
make_clip_video(path1, os.path.join(base_save_path, 'b_119_broken_30.mp4'), 30, 32)
make_clip_video(path1, os.path.join(base_save_path, 'b_120_broken_31.mp4'), 36, 38)
make_clip_video(path1, os.path.join(base_save_path, 'b_121_broken_32.mp4'), 40, 43)

#2
make_clip_video(path2, os.path.join(base_save_path, 'b_122_broken_36.mp4'), 26, 27)
make_clip_video(path2, os.path.join(base_save_path, 'b_123_broken_30.mp4'), 30, 32)
make_clip_video(path2, os.path.join(base_save_path, 'b_124_broken_31.mp4'), 36, 38)
make_clip_video(path2, os.path.join(base_save_path, 'b_125_broken_32.mp4'), 40, 43)

#3
make_clip_video(path3, os.path.join(base_save_path, 'b_126_broken_36.mp4'), 26, 27)
make_clip_video(path3, os.path.join(base_save_path, 'b_127_broken_30.mp4'), 30, 32)
make_clip_video(path3, os.path.join(base_save_path, 'b_128_broken_31.mp4'), 36, 38)
make_clip_video(path3, os.path.join(base_save_path, 'b_129_broken_32.mp4'), 40, 43)


# 4
make_clip_video(path4, os.path.join(base_save_path, 'b_130_broken_36.mp4'), 26, 27)
make_clip_video(path4, os.path.join(base_save_path, 'b_131_broken_30.mp4'), 30, 32)
make_clip_video(path4, os.path.join(base_save_path, 'b_132_broken_31.mp4'), 36, 38)
make_clip_video(path4, os.path.join(base_save_path, 'b_133_broken_32.mp4'), 40, 43)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_118_broken_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_119_broken_30.mp4"))
abnormal3 = VideoFileClip(os.path.join(source_path, "b_120_broken_31.mp4"))
abnormal4 = VideoFileClip(os.path.join(source_path, "b_121_broken_32.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2, abnormal3, abnormal4])

combined_a.write_videofile(os.path.join(save_path, "bcom_020_broken_66.mp4"))


#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_122_broken_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_123_broken_30.mp4"))
abnormal3 = VideoFileClip(os.path.join(source_path, "b_124_broken_31.mp4"))
abnormal4 = VideoFileClip(os.path.join(source_path, "b_125_broken_32.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2, abnormal3, abnormal4])

combined_a.write_videofile(os.path.join(save_path, "bcom_021_broken_66.mp4"))


#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_126_broken_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_127_broken_30.mp4"))
abnormal3 = VideoFileClip(os.path.join(source_path, "b_128_broken_31.mp4"))
abnormal4 = VideoFileClip(os.path.join(source_path, "b_129_broken_32.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2, abnormal3, abnormal4])

combined_a.write_videofile(os.path.join(save_path, "bcom_022_broken_66.mp4"))

#4
abnormal1 = VideoFileClip(os.path.join(source_path, "b_130_broken_36.mp4"))
abnormal2 = VideoFileClip(os.path.join(source_path, "b_131_broken_30.mp4"))
abnormal3 = VideoFileClip(os.path.join(source_path, "b_132_broken_31.mp4"))
abnormal4 = VideoFileClip(os.path.join(source_path, "b_133_broken_32.mp4"))

combined_a = concatenate_videoclips([abnormal1, abnormal2, abnormal3, abnormal4])

combined_a.write_videofile(os.path.join(save_path, "bcom_023_broken_66.mp4"))

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_13.폭행/C_3_13_1_BU_DYA_08-28_11-26-41_CA_RGB_DF2_M1.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_13.폭행/C_3_13_1_BU_DYA_08-28_11-26-41_CB_RGB_DF2_M1.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_13.폭행/C_3_13_1_BU_DYA_08-28_11-26-41_CC_RGB_DF2_M1.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_13.폭행/C_3_13_1_BU_DYA_08-28_11-26-41_CD_RGB_DF2_M1.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_118_violence_36.mp4'), 27,53)

#2
make_clip_video(path2, os.path.join(base_save_path, 'b_119_violence_36.mp4'), 27,53)

#3
make_clip_video(path3, os.path.join(base_save_path, 'b_120_violence_36.mp4'), 27,53)

# 4
make_clip_video(path4, os.path.join(base_save_path, 'b_121_violence_36.mp4'), 27,53)

#1
abnormal1 = VideoFileClip(os.path.join(source_path, "b_118_violence_36.mp4"))

combined_a = concatenate_videoclips([abnormal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_020_violence_66.mp4"))

#2
abnormal1 = VideoFileClip(os.path.join(source_path, "b_119_violence_36.mp4"))

combined_a = concatenate_videoclips([abnormal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_021_violence_66.mp4"))

#3
abnormal1 = VideoFileClip(os.path.join(source_path, "b_120_violence_36.mp4"))

combined_a = concatenate_videoclips([abnormal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_022_violence_66.mp4"))

#4
abnormal1 = VideoFileClip(os.path.join(source_path, "b_121_violence_36.mp4"))

combined_a = concatenate_videoclips([abnormal1])

combined_a.write_videofile(os.path.join(save_path, "bcom_023_violence_66.mp4"))

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_6_BU_SMA_08-28_13-46-05_CC_RGB_DF2_F1.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_6_BU_SMA_08-28_13-46-05_CD_RGB_DF2_F1.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_6_BU_SMA_08-28_13-46-06_CA_RGB_DF2_F1.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_6_BU_SMA_08-28_13-46-06_CB_RGB_DF2_F1.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_127_broken_36.mp4'), 28,34)
make_clip_video(path1, os.path.join(base_save_path, 'b_128_broken_36.mp4'), 37,43)
make_clip_video(path1, os.path.join(base_save_path, 'b_129_broken_36.mp4'), 50,53)
#2
make_clip_video(path2, os.path.join(base_save_path, 'b_130_broken_36.mp4'), 28,34)
make_clip_video(path2, os.path.join(base_save_path, 'b_131_broken_36.mp4'), 37,43)
make_clip_video(path2, os.path.join(base_save_path, 'b_132_broken_36.mp4'), 50,53)

#3
make_clip_video(path3, os.path.join(base_save_path, 'b_134_broken_36.mp4'), 28,34)
make_clip_video(path3, os.path.join(base_save_path, 'b_135_broken_36.mp4'), 37,43)
make_clip_video(path3, os.path.join(base_save_path, 'b_136_broken_36.mp4'), 50,53)

# 4
make_clip_video(path4, os.path.join(base_save_path, 'b_137_broken_36.mp4'), 28,34)
make_clip_video(path4, os.path.join(base_save_path, 'b_138_broken_36.mp4'), 37,43)
make_clip_video(path4, os.path.join(base_save_path, 'b_139_broken_36.mp4'), 50,53)

path1 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_7_BU_SMA_09-07_14-35-52_CA_RGB_DF2_M2.mp4'
path2 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_7_BU_SMA_09-07_14-35-52_CB_RGB_DF2_M2.mp4'
path3 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_7_BU_SMA_09-07_14-35-52_CC_RGB_DF2_M2.mp4'
path4 = '/content/drive/MyDrive/CCTV/TS_03.이상행동_08.파손/C_3_8_7_BU_SMA_09-07_14-35-52_CD_RGB_DF2_M2.mp4'

#1
make_clip_video(path1, os.path.join(base_save_path, 'b_140_broken_36.mp4'), 24,25)
make_clip_video(path1, os.path.join(base_save_path, 'b_141_broken_36.mp4'), 32,33)
make_clip_video(path1, os.path.join(base_save_path, 'b_142_broken_36.mp4'), 39,42)
make_clip_video(path1, os.path.join(base_save_path, 'b_141_broken_36.mp4'), 48,51)

#2
make_clip_video(path2, os.path.join(base_save_path, 'b_142_broken_36.mp4'), 24,25)
make_clip_video(path2, os.path.join(base_save_path, 'b_143_broken_36.mp4'), 32,33)
make_clip_video(path2, os.path.join(base_save_path, 'b_144_broken_36.mp4'), 39,42)
make_clip_video(path2, os.path.join(base_save_path, 'b_145_broken_36.mp4'), 48,51)
#3
make_clip_video(path3, os.path.join(base_save_path, 'b_146_broken_36.mp4'), 24,25)
make_clip_video(path3, os.path.join(base_save_path, 'b_147_broken_36.mp4'), 32,33)
make_clip_video(path3, os.path.join(base_save_path, 'b_148_broken_36.mp4'), 39,42)
make_clip_video(path3, os.path.join(base_save_path, 'b_149_broken_36.mp4'), 48,51)

# 4
make_clip_video(path4, os.path.join(base_save_path, 'b_150_broken_36.mp4'), 24,25)
make_clip_video(path4, os.path.join(base_save_path, 'b_151_broken_36.mp4'), 32,33)
make_clip_video(path4, os.path.join(base_save_path, 'b_152_broken_36.mp4'), 39,42)
make_clip_video(path4, os.path.join(base_save_path, 'b_153_broken_36.mp4'), 48,51)

